spring:
  application:
    name: Authentication-Service

  profiles:
    # Let env decide; default to dev if nothing is set
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/backend_user_management?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}


server:
  port: ${SERVER_PORT:8092}

sms:
  base-url: ${SMS_BASE_URL:https://api.mylogin.co.in/api/v2}
  api-key: ${SMS_API_KEY:N9v15Ydho0qL84kMBQGmAMmdE5vfG61D+TF8Nc+X80s=}
  client-id: ${SMS_CLIENT_ID:c5ece875-8559-4e64-805f-c658f0dddc93}
  sender-id: ${SMS_SENDER_ID:MCPNOT}
  dlt:
    template-id: ${SMS_DLT_TEMPLATE_ID:1407175378487206260}
    content: ${SMS_DLT_CONTENT:"Your MOC OTP is {#var#}. It is valid for 10 minutes. Do not share this OTP with anyone for security reasons from MOC Connect Private Limited."}
  otp:
    ttl-minutes: ${SMS_OTP_TTL_MINUTES:10}
    digits: ${SMS_OTP_DIGITS:6}
    per-minute-limit: ${SMS_OTP_PER_MINUTE_LIMIT:1}
    per-hour-limit: ${SMS_OTP_PER_HOUR_LIMIT:5}


jwt:
  alg: RS256
  issuer: ${JWT_ISSUER:http://auth-service:8092}       # set to your real base URL/host:port
  kid: ${JWT_KID::main-2025-08-16}                  # any stable ID for this key
  private-key-pem: ${JWT_PRIVATE_KEY_PEM} # full PKCS#8 PEM text via env var

  # optional rotation support (publish old public key alongside the new one)
  previous-kid: ${JWT_PREV_KID:}
  previous-public-pem: ${JWT_PREV_PUBLIC_PEM:}
  access-ttl-min: ${JWT_ACCESS_TTL_MIN:15}
  refresh-ttl-days: ${JWT_REFRESH_TTL_DAYS:30}

media:
  bucket: ${MEDIA_BUCKET:moc-prod}   # default "moc-prod", override via env var MEDIA_BUCKET

# (recommended—where to call RTC)
rtc:
  base-url: ${RTC_BASE_URL:http://rtc-service:8095}

# optional, nice-to-have knobs used by AvatarService
avatar:
  max-size-bytes: ${AVATAR_MAX_SIZE_BYTES:5242880}      # 5 MB
  put-url-ttl-seconds: ${AVATAR_PUT_TTL_SECONDS:600}
  get-url-ttl-seconds: ${AVATAR_GET_TTL_SECONDS:600}


# Keep this custom and read it in a @ConfigurationProperties or @Value
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,capacitor://localhost}
